-- VECTOR / GQH Snowflake bootstrap
-- Review before running. No warehouse is created here.
-- Snowflake stays off the live order path; TigerData/q handle execution data.

CREATE DATABASE IF NOT EXISTS VECTOR_RESEARCH;
CREATE SCHEMA IF NOT EXISTS VECTOR_RESEARCH.RAW;
CREATE SCHEMA IF NOT EXISTS VECTOR_RESEARCH.NORMALIZED;
CREATE SCHEMA IF NOT EXISTS VECTOR_RESEARCH.FEATURES;
CREATE SCHEMA IF NOT EXISTS VECTOR_RESEARCH.RESEARCH;

CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.RAW.AWS_GPU_SPOT_PRICES (
  price_time TIMESTAMP_TZ NOT NULL,
  zone_id VARCHAR NOT NULL,
  instance_type VARCHAR NOT NULL,
  operating_system VARCHAR NOT NULL,
  usd_per_instance_hour NUMBER(24,9) NOT NULL,
  source_file VARCHAR NOT NULL,
  source_doi VARCHAR NOT NULL,
  source_md5 VARCHAR NOT NULL,
  license VARCHAR NOT NULL,
  ingested_at TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (price_time, zone_id, instance_type, operating_system, source_file)
);
-- This source has a documented archive gap. Keep it explicit instead of filling it.
CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.RAW.AWS_GPU_SPOT_SOURCE_GAPS (
  source_doi VARCHAR NOT NULL,
  start_time TIMESTAMP_TZ NOT NULL,
  end_time_exclusive TIMESTAMP_TZ NOT NULL,
  reason VARCHAR NOT NULL,
  PRIMARY KEY (source_doi, start_time)
);

INSERT INTO VECTOR_RESEARCH.RAW.AWS_GPU_SPOT_SOURCE_GAPS
  (source_doi, start_time, end_time_exclusive, reason)
SELECT '10.5281/zenodo.23082767', '2026-03-01T00:00:00Z', '2026-07-01T00:00:00Z',
       'March through June absent from source archive; do not interpolate as observed prices'
WHERE NOT EXISTS (
  SELECT 1 FROM VECTOR_RESEARCH.RAW.AWS_GPU_SPOT_SOURCE_GAPS
  WHERE source_doi = '10.5281/zenodo.23082767'
    AND start_time = TO_TIMESTAMP_TZ('2026-03-01T00:00:00Z')
);

-- Descriptive daily rollup only. Historical collector availability is unknown, so this
-- view must not be joined as an available-at-the-time trading feature without new evidence.
CREATE VIEW IF NOT EXISTS VECTOR_RESEARCH.NORMALIZED.AWS_GPU_SPOT_DAILY AS
SELECT
  DATE_TRUNC('DAY', price_time) AS event_day,
  zone_id,
  instance_type,
  operating_system,
  COUNT(*) AS quote_count,
  MIN(usd_per_instance_hour) AS min_usd_per_instance_hour,
  MEDIAN(usd_per_instance_hour) AS median_usd_per_instance_hour,
  MAX(usd_per_instance_hour) AS max_usd_per_instance_hour,
  MIN(price_time) AS first_observation_at,
  MAX(price_time) AS last_observation_at
FROM VECTOR_RESEARCH.RAW.AWS_GPU_SPOT_PRICES
GROUP BY 1, 2, 3, 4;

CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.RAW.FILINGS_8K (
  filing_id VARCHAR NOT NULL,
  issuer_cik VARCHAR NOT NULL,
  ticker VARCHAR,
  filed_at TIMESTAMP_TZ NOT NULL,
  available_at TIMESTAMP_TZ NOT NULL,
  form_type VARCHAR NOT NULL,
  accession_number VARCHAR NOT NULL,
  item_codes ARRAY,
  filing_text VARCHAR,
  source_url VARCHAR,
  source_version VARCHAR,
  ingested_at TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (issuer_cik, accession_number)
);

CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.RAW.EQUITY_BARS (
  ticker VARCHAR NOT NULL,
  event_time TIMESTAMP_TZ NOT NULL,
  open NUMBER(24,9),
  high NUMBER(24,9),
  low NUMBER(24,9),
  close NUMBER(24,9),
  volume NUMBER(38,0),
  source VARCHAR NOT NULL,
  source_version VARCHAR,
  ingested_at TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (ticker, event_time, source)
);

CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.FEATURES.POINT_IN_TIME_PANEL (
  ticker VARCHAR NOT NULL,
  decision_time TIMESTAMP_TZ NOT NULL,
  compute_price NUMBER(24,9),
  compute_price_time TIMESTAMP_TZ,
  compute_age_seconds NUMBER(38,0),
  regional_spread NUMBER(24,9),
  filing_id VARCHAR,
  filing_available_at TIMESTAMP_TZ,
  return_1d NUMBER(24,12),
  volatility_20d NUMBER(24,12),
  feature_version VARCHAR NOT NULL,
  created_at TIMESTAMP_TZ NOT NULL
);

-- Versioned issuer-event research contract. These tables are additive to the earlier generic
-- prototype above. Feature inputs and realized labels are separate so a strategy query cannot
-- accidentally consume a forward return. Loader code must enforce idempotency and uniqueness;
-- Snowflake primary-key declarations are informational on standard tables.
CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.NORMALIZED.OPERATIONAL_FACTS (
  EVENT_ID VARCHAR NOT NULL,
  EVENT_CLUSTER_ID VARCHAR,
  ISSUER_CIK VARCHAR NOT NULL,
  TICKER VARCHAR,
  SECURITY_ID VARCHAR,
  ACCESSION VARCHAR NOT NULL,
  FORM VARCHAR NOT NULL,
  FILED_AT_UTC TIMESTAMP_TZ,
  ACCEPTED_AT_UTC TIMESTAMP_TZ,
  FIRST_PUBLIC_AT_UTC TIMESTAMP_TZ,
  AVAILABLE_AT_UTC TIMESTAMP_TZ NOT NULL,
  AVAILABILITY_METHOD VARCHAR NOT NULL,
  ECONOMIC_PERIOD_START DATE,
  ECONOMIC_PERIOD_END DATE,
  TARGET_PERIOD VARCHAR,
  METRIC_NAME VARCHAR NOT NULL,
  XBRL_CONCEPT VARCHAR,
  SEGMENT VARCHAR,
  PROJECT_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  COUNTERPARTY_ID VARCHAR,
  FACT_KIND VARCHAR NOT NULL,
  VALUE_TEXT VARCHAR,
  VALUE_DECIMAL NUMBER(38,12),
  PRIOR_VALUE_DECIMAL NUMBER(38,12),
  DELTA_DECIMAL NUMBER(38,12),
  UNIT VARCHAR,
  CURRENCY VARCHAR,
  SCOPE_TEXT VARCHAR,
  DEFINITION_VERSION VARCHAR,
  EXPECTATION_TYPE VARCHAR,
  EXPECTATION_VALUE NUMBER(38,12),
  EXPECTATION_AVAILABLE_AT_UTC TIMESTAMP_TZ,
  EXPOSURE_STATUS VARCHAR NOT NULL,
  EXPOSURE_FRACTION NUMBER(18,12),
  EXPOSURE_EVIDENCE_ID VARCHAR,
  EXTRACTOR_VERSION VARCHAR NOT NULL,
  REVIEW_STATUS VARCHAR NOT NULL,
  SOURCE_SPAN VARCHAR,
  CONFIDENCE NUMBER(8,7),
  SOURCE_DOCUMENT_URL VARCHAR NOT NULL,
  DOCUMENT_SHA256 VARCHAR NOT NULL,
  INPUT_BATCH_SHA256 VARCHAR NOT NULL,
  RETRIEVED_AT_UTC TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (EVENT_ID, DOCUMENT_SHA256, EXTRACTOR_VERSION)
);

CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.FEATURES.EQUITY_EVENT_FEATURES (
  EVENT_ID VARCHAR NOT NULL,
  FEATURE_VERSION VARCHAR NOT NULL,
  DECISION_AT_UTC TIMESTAMP_TZ NOT NULL,
  AVAILABLE_AT_UTC TIMESTAMP_TZ NOT NULL,
  ISSUER_CIK VARCHAR NOT NULL,
  TICKER VARCHAR NOT NULL,
  SECURITY_ID VARCHAR,
  EVENT_CLUSTER_ID VARCHAR,
  METRIC_NAME VARCHAR NOT NULL,
  FACT_KIND VARCHAR NOT NULL,
  REVISION_ABS NUMBER(38,12),
  REVISION_PCT NUMBER(24,12),
  REVISION_VS_PAST_MEDIAN NUMBER(38,12),
  PAST_MAD_Z NUMBER(24,12),
  N_PRIOR_EVENTS NUMBER(38,0) NOT NULL,
  EXPECTATION_TYPE VARCHAR,
  EXPOSURE_STATUS VARCHAR NOT NULL,
  EXPOSURE_FRACTION NUMBER(18,12),
  TRAILING_RETURN_1D NUMBER(24,12),
  TRAILING_RETURN_5D NUMBER(24,12),
  TRAILING_RETURN_20D NUMBER(24,12),
  MARKET_RETURN_20D NUMBER(24,12),
  SECTOR_RETURN_20D NUMBER(24,12),
  BETA_MARKET_PAST NUMBER(24,12),
  BETA_SECTOR_PAST NUMBER(24,12),
  REALIZED_VOL_20D NUMBER(24,12),
  DOLLAR_VOLUME_20D NUMBER(38,8),
  MISSING_BAR_FLAG BOOLEAN NOT NULL,
  CORPORATE_ACTION_FLAG BOOLEAN NOT NULL,
  PRICE_BATCH_SHA256 VARCHAR NOT NULL,
  FACT_BATCH_SHA256 VARCHAR NOT NULL,
  FEATURE_INPUTS_JSON VARIANT NOT NULL,
  CREATED_AT_UTC TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (EVENT_ID, FEATURE_VERSION)
);

CREATE TABLE IF NOT EXISTS VECTOR_RESEARCH.FEATURES.EQUITY_EVENT_LABELS (
  EVENT_ID VARCHAR NOT NULL,
  LABEL_VERSION VARCHAR NOT NULL,
  HORIZON_SESSIONS NUMBER(5,0) NOT NULL,
  ENTRY_REFERENCE_AT_UTC TIMESTAMP_TZ,
  LABEL_START_AT_UTC TIMESTAMP_TZ,
  LABEL_END_AT_UTC TIMESTAMP_TZ,
  RAW_RETURN NUMBER(24,12),
  BENCHMARK_RETURN NUMBER(24,12),
  SECTOR_RETURN NUMBER(24,12),
  ABNORMAL_RETURN NUMBER(24,12),
  ESTIMATED_COST_BPS NUMBER(18,8),
  NET_ABNORMAL_RETURN NUMBER(24,12),
  INPUT_PRICE_BATCH_SHA256 VARCHAR NOT NULL,
  CREATED_AT_UTC TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (EVENT_ID, LABEL_VERSION, HORIZON_SESSIONS)
);

-- Post-load QA query. Expected for the current 2026-09 snapshot:
-- 1,592,024 rows, 31 source files, source period 2022-05-31 through 2026-09-30,
-- no null ingestion timestamps, and zero observations in the Mar-Jun 2026 gap.
SELECT
  COUNT(*) AS row_count,
  COUNT(DISTINCT source_file) AS source_file_count,
  MIN(price_time) AS min_price_time,
  TO_VARCHAR(MIN(price_time)) AS min_price_time_text,
  MAX(price_time) AS max_price_time,
  TO_VARCHAR(MAX(price_time)) AS max_price_time_text,
  COUNT_IF(ingested_at IS NULL) AS null_ingested_at_count,
  COUNT_IF(price_time >= TO_TIMESTAMP_TZ('2026-03-01T00:00:00Z')
       AND price_time < TO_TIMESTAMP_TZ('2026-07-01T00:00:00Z')) AS rows_in_source_gap
FROM VECTOR_RESEARCH.RAW.AWS_GPU_SPOT_PRICES;
