#!/usr/bin/env python3
"""Filter local memory entries into a form that is safe to commit to a public repo.

Two rules, in this order:

1. Default deny. An entry is shared only when it carries the share tag.
2. Redact, then drop. Any entry whose content still looks like it carries a live
   credential or a machine-specific path is dropped rather than published.

Used by `make share`. Tested by tests/test_memory_filter.py.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HOME = re.compile(r"/home/[A-Za-z0-9._-]+")
WIN_HOME = re.compile(r"(/mnt/[a-z]/Users/|[A-Za-z]:\\Users\\)[A-Za-z0-9._-]+")
MAC_HOME = re.compile(r"/Users/[A-Za-z0-9._-]+")

# Assignment of a credential-looking name to a value.
# A credential name assigned to a value. The value must look like a value: at least
# six characters from the key alphabet, optionally quoted. This keeps prose such as
# "never commit api keys" out of the net while still catching a pasted key.
SECRET_ASSIGNMENT = re.compile(
    r"(?i)\b(api[_-]?key|apikey|secret|client[_-]?secret|password|passwd|passphrase"
    r"|private[_-]?key|access[_-]?token|auth[_-]?token|refresh[_-]?token|token|bearer)\b"
    r"\s*[:=]\s*[\"']?[A-Za-z0-9_.\-]{6,}"
)

# Credential value shapes, even without a name in front.
SECRET_VALUE = re.compile(
    r"(sk-[A-Za-z0-9_\-]{12,}"
    r"|sk_(live|test)_[A-Za-z0-9]{12,}"
    r"|gh[pousr]_[A-Za-z0-9]{20,}"
    r"|github_pat_[A-Za-z0-9_]{20,}"
    r"|AKIA[0-9A-Z]{16}"
    r"|AIza[0-9A-Za-z_\-]{30,}"
    r"|xox[baprs]-[A-Za-z0-9\-]{10,}"
    r"|-----BEGIN [A-Z ]*PRIVATE KEY-----"
    r"|eyJ[A-Za-z0-9_\-]{20,}\.[A-Za-z0-9_\-]{20,}\.)"
)

PATH_TAG = re.compile(r"^(path:|device:|host:)")

# The repo root this script lives in. Paths under it collapse to <repo> so the
# private workspace layout does not travel with the memory.
REPO_ROOT = Path(__file__).resolve().parent.parent


def redact(text: str, repo_root: Path | None = None) -> str:
    """Rewrite machine specific paths so the text is portable."""
    root = repo_root or REPO_ROOT
    out = text.replace(str(root), "<repo>")
    out = HOME.sub("<home>", out)
    out = WIN_HOME.sub(r"<win-home>", out)
    out = MAC_HOME.sub("<home>", out)
    return out


def looks_secret(text: str) -> bool:
    return bool(SECRET_VALUE.search(text) or SECRET_ASSIGNMENT.search(text))


PROJECT_TAGS = ("quanthacks", "gator-quant-hacks")


def filter_entries(entries, share_tag: str = "gqh", store_scoped: bool = False):
    """Return the shareable subset, redacted, deduped by id, sorted by id.

    store_scoped=True means the memory store lives inside the repo, so every entry in
    it is project scope by construction and no human tagging is required. Otherwise
    the default is deny and the share tag decides.
    """
    kept: dict[str, dict] = {}
    for raw in entries:
        if not isinstance(raw, dict):
            continue
        tags = [str(t) for t in raw.get("tags", []) or []]
        tagged = share_tag in tags or any(t in PROJECT_TAGS for t in tags)
        if not tagged and not store_scoped:
            continue
        content = redact(str(raw.get("content", "")))
        if not content.strip() or looks_secret(content):
            continue
        clean_tags = [t for t in tags if not PATH_TAG.match(t)]
        if share_tag not in clean_tags:
            clean_tags.insert(0, share_tag)
        item = {
            "id": str(raw.get("id", "")) or f"mem_{abs(hash(content)):x}",
            "content": content,
            "tags": clean_tags,
        }
        for key in ("created", "layer", "confidence", "pinned"):
            if key in raw:
                item[key] = raw[key]
        kept.setdefault(item["id"], item)
    return [kept[k] for k in sorted(kept)]


def render_markdown(entries) -> str:
    lines = [
        "# Shared memory",
        "",
        "Generated by `make share`. Do not edit by hand: edit `docs/`, or write a memory",
        "locally with the `gqh` tag and run `make share` again.",
        "",
        f"{len(entries)} entries. Import into a local store with `make absorb`.",
        "",
    ]
    for item in entries:
        tags = ", ".join(item.get("tags", []))
        lines.append(f"## {item['id']}")
        lines.append("")
        lines.append(f"- tags: {tags}")
        if item.get("created"):
            lines.append(f"- created: {item['created']}")
        lines.append("")
        lines.append(item["content"].strip())
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    args = [a for a in argv[1:] if not a.startswith("--")]
    store_scoped = "--store-scoped" in argv
    if len(args) != 2:
        print("usage: memory_filter.py [--store-scoped] <raw-export.json> <out-dir>",
              file=sys.stderr)
        return 2
    raw_path, out_dir = Path(args[0]), Path(args[1])
    entries = json.loads(raw_path.read_text()) if raw_path.exists() else []
    if isinstance(entries, dict):
        entries = entries.get("memories", [])
    shared = filter_entries(entries, store_scoped=store_scoped)

    # Merge with what is already in the file: the shared memory is a union across
    # devices, so a device never removes an entry it simply cannot see.
    existing_path = Path(out_dir) / "shared.json"
    if existing_path.exists():
        try:
            existing = json.loads(existing_path.read_text())
        except json.JSONDecodeError:
            existing = []
        by_content = {}
        for item in list(shared) + list(existing):
            if not isinstance(item, dict):
                continue
            key = " ".join(str(item.get("content", "")).split())
            if key and key not in by_content:
                by_content[key] = item
        shared = sorted(by_content.values(), key=lambda item: str(item.get("id", "")))

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "shared.json").write_text(json.dumps(shared, indent=2) + "\n")
    (out_dir / "SHARED.md").write_text(render_markdown(shared))
    print(f"{len(entries)} local entries -> {len(shared)} shared (union with the committed file)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
