#!/usr/bin/env python3
"""Render the QuantGraph declarations as one self-contained page.

Reads `docs/scan/quantgraph.jsonl` and writes:

  docs/scan/quantgraph.html   interactive: pan, zoom, hover, layer and status filters
  docs/scan/quantgraph.svg    the same layout as a static image

The layout is a deterministic force layout (numpy, seed 42), so the same manifest
always produces the same picture. No network, no extra dependency beyond numpy.

    python3 scripts/render_quantgraph_viz.py
"""
from __future__ import annotations

import colorsys
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs" / "scan" / "quantgraph.jsonl"
HTML = ROOT / "docs" / "scan" / "quantgraph.html"
SVG = ROOT / "docs" / "scan" / "quantgraph.svg"

WIDTH, HEIGHT = 1500, 950
ITERATIONS = 260
SEED = 42
LABEL_COUNT = 45

LAYER_COLORS = {
    "source": "#1f77b4", "dataset": "#2ca02c", "raw": "#8c564b", "feature": "#17becf",
    "entity": "#9467bd", "event": "#e377c2", "mechanism": "#d62728", "assumption": "#7f7f7f",
    "outcome": "#ff7f0e", "claim": "#bcbd22", "strategy": "#393b79", "rule": "#637939",
    "evidence": "#8c6d31", "experiment": "#843c39", "implementation": "#7b4173",
    "contract": "#5254a3", "factor": "#9c9ede", "asset": "#a55194", "concept": "#6b6ecf",
}


def load() -> tuple[list[dict], list[dict]]:
    nodes, edges = [], []
    for line in MANIFEST.read_text().splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        (nodes if record.get("kind") == "node" else edges).append(record)
    return nodes, edges


def layer_color(layer: str) -> str:
    if layer in LAYER_COLORS:
        return LAYER_COLORS[layer]
    hue = (abs(hash(layer)) % 360) / 360
    return "#" + "".join(f"{int(255 * value):02x}" for value in colorsys.hsv_to_rgb(hue, 0.55, 0.8))


def layout(nodes: list[dict], edges: list[dict]) -> dict[str, tuple[float, float]]:
    index = {node["id"]: i for i, node in enumerate(nodes)}
    count = len(nodes)
    rng = np.random.default_rng(SEED)
    pos = rng.normal(size=(count, 2)) * 3.0
    pos -= pos.mean(axis=0)
    pairs = [(index[edge["from"]], index[edge["to"]]) for edge in edges
             if edge.get("from") in index and edge.get("to") in index]
    src = np.array([pair[0] for pair in pairs]) if pairs else np.zeros(0, dtype=int)
    dst = np.array([pair[1] for pair in pairs]) if pairs else np.zeros(0, dtype=int)
    k = np.sqrt(4.0 / count) * 1.6
    temperature = k * 1.6
    for _ in range(ITERATIONS):
        delta = pos[:, None, :] - pos[None, :, :]
        distance = np.sqrt((delta ** 2).sum(-1)) + 1e-9
        repulsion = (k * k / distance ** 2)[:, :, None] * delta / distance[:, :, None]
        np.fill_diagonal(repulsion[:, :, 0], 0.0)
        np.fill_diagonal(repulsion[:, :, 1], 0.0)
        force = repulsion.sum(axis=1)
        if len(src):
            pull = pos[src] - pos[dst]
            length = np.sqrt((pull ** 2).sum(1)) + 1e-9
            attraction = (length / k)[:, None] * pull / length[:, None]
            for dimension in (0, 1):
                force[:, dimension] += (np.bincount(src, weights=attraction[:, dimension], minlength=count)
                                        - np.bincount(dst, weights=attraction[:, dimension], minlength=count))
        length = np.sqrt((force ** 2).sum(1)) + 1e-9
        step = force / length[:, None] * np.minimum(length, temperature)[:, None]
        pos += step
        temperature = max(temperature * 0.985, k * 0.01)
    pos -= pos.min(axis=0)
    span = pos.max(axis=0) - pos.min(axis=0)
    span[span == 0] = 1.0
    scale = np.array([WIDTH - 80, HEIGHT - 80]) / span
    pos *= scale
    pos += 40
    pos[:, 1] = HEIGHT - pos[:, 1]
    return {node["id"]: (float(pos[i, 0]), float(pos[i, 1])) for i, node in enumerate(nodes)}


def degree_of(edges: list[dict]) -> dict[str, int]:
    degree: dict[str, int] = {}
    for edge in edges:
        degree[edge["from"]] = degree.get(edge["from"], 0) + 1
        degree[edge["to"]] = degree.get(edge["to"], 0) + 1
    return degree


def build_svg(nodes, edges, positions, degree) -> str:
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" width="100%">',
             '<!-- generated by scripts/render_quantgraph_viz.py from docs/scan/quantgraph.jsonl -->',
             f'<rect width="{WIDTH}" height="{HEIGHT}" fill="#ffffff"/>',
             '<g stroke-linecap="round">']
    for edge in edges:
        start, end = positions.get(edge.get("from")), positions.get(edge.get("to"))
        if not start or not end:
            continue
        if edge.get("status") == "proposed":
            parts.append(f'<line x1="{start[0]:.1f}" y1="{start[1]:.1f}" x2="{end[0]:.1f}" '
                         f'y2="{end[1]:.1f}" stroke="#dfe6ee" stroke-width="0.7"/>')
        elif edge.get("status") == "blocked":
            parts.append(f'<line x1="{start[0]:.1f}" y1="{start[1]:.1f}" x2="{end[0]:.1f}" '
                         f'y2="{end[1]:.1f}" stroke="#e9a6a6" stroke-width="0.9"/>')
        else:
            parts.append(f'<line x1="{start[0]:.1f}" y1="{start[1]:.1f}" x2="{end[0]:.1f}" '
                         f'y2="{end[1]:.1f}" stroke="#b9c6d4" stroke-width="0.8"/>')
    parts.append("</g>")
    ranked = sorted(nodes, key=lambda node: -degree.get(node["id"], 0))
    labelled = {node["id"] for node in ranked[:LABEL_COUNT]}
    for node in nodes:
        x, y = positions[node["id"]]
        radius = 2.6 + min(9.0, (degree.get(node["id"], 0) ** 0.5) * 0.9)
        color = layer_color(node.get("layer", ""))
        opacity = 0.45 if node.get("status") == "proposed" else 0.95
        if node.get("status") == "blocked":
            parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{radius:.1f}" fill="#ffffff" '
                         f'stroke="#cc0000" stroke-width="1.4"/>')
        else:
            parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{radius:.1f}" fill="{color}" '
                         f'fill-opacity="{opacity}"/>')
        if node["id"] in labelled:
            short = node["id"].split(":", 1)[-1]
            parts.append(f'<text x="{x + radius + 2:.1f}" y="{y + 3:.1f}" font-size="9.5" '
                         f'fill="#333">{short}</text>')
    parts.append("</svg>")
    return "\n".join(parts)


def build_html(nodes, edges, positions, degree) -> str:
    payload = {
        "nodes": [{"id": node["id"], "layer": node.get("layer", ""), "status": node.get("status", ""),
                   "meaning": node.get("meaning", ""), "unit": node.get("unit", ""),
                   "roles": node.get("roles", []), "falsifier": node.get("falsifier", ""),
                   "x": positions[node["id"]][0], "y": positions[node["id"]][1],
                   "degree": degree.get(node["id"], 0), "color": layer_color(node.get("layer", ""))}
                  for node in nodes],
        "edges": [{"from": edge["from"], "to": edge["to"], "relation": edge.get("relation", ""),
                   "status": edge.get("status", "")} for edge in edges],
        "width": WIDTH, "height": HEIGHT,
    }
    return HTML_TEMPLATE.replace("__DATA__", json.dumps(payload, separators=(",", ":")))


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>QuantGraph declarations</title>
<style>
  html, body { margin: 0; height: 100%; font: 13px/1.4 -apple-system, Segoe UI, Roboto, sans-serif; }
  #stage { position: fixed; inset: 0; background: #fff; cursor: grab; }
  #stage.dragging { cursor: grabbing; }
  #panel { position: fixed; top: 10px; left: 10px; background: rgba(255,255,255,.94);
           border: 1px solid #ccd; border-radius: 8px; padding: 10px 12px; max-width: 300px; }
  #panel h1 { font-size: 14px; margin: 0 0 4px 0; }
  #panel .stats { color: #555; margin-bottom: 8px; }
  #tooltip { position: fixed; pointer-events: none; background: rgba(20,24,30,.94); color: #fff;
             padding: 7px 9px; border-radius: 6px; max-width: 320px; display: none; font-size: 12px; }
  .legend { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 10px; margin: 6px 0; }
  .legend label { display: flex; align-items: center; gap: 5px; cursor: pointer; font-size: 12px; }
  .legend .dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
  .row { margin: 6px 0; }
  .row label { margin-right: 8px; }
  button, input[type=search] { font: inherit; padding: 3px 6px; }
</style>
</head>
<body>
<canvas id="stage"></canvas>
<div id="panel">
  <h1>QuantGraph declarations</h1>
  <div class="stats">generated by scripts/render_quantgraph_viz.py from docs/scan/quantgraph.jsonl</div>
  <div class="stats" id="stats"></div>
  <div class="row"><input type="search" id="search" placeholder="highlight a node id" style="width: 150px"> <button id="reset">reset</button></div>
  <div class="row">
    <label><input type="checkbox" data-status="declared" checked> declared</label>
    <label><input type="checkbox" data-status="proposed" checked> proposed</label>
    <label><input type="checkbox" data-status="blocked" checked> blocked</label>
  </div>
  <div class="legend" id="legend"></div>
  <div class="stats">scroll to zoom, drag to pan, hover a node. Edge colours: declared, proposed, blocked.</div>
</div>
<div id="tooltip"></div>
<script>
const DATA = __DATA__;
const canvas = document.getElementById("stage");
const ctx = canvas.getContext("2d");
const tooltip = document.getElementById("tooltip");
const byId = new Map(DATA.nodes.map(n => [n.id, n]));
const hiddenLayers = new Set();
const hiddenStatus = new Set();
const transform = { x: 0, y: 0, scale: 1 };
const view = { width: 0, height: 0 };
let hovered = null, pinned = null, matches = new Set();

function fitView() {
  const scale = Math.min(view.width / DATA.width, view.height / DATA.height) * 0.94;
  transform.scale = scale;
  transform.x = (view.width - DATA.width * scale) / 2;
  transform.y = (view.height - DATA.height * scale) / 2;
}
function fit() {
  view.width = window.innerWidth; view.height = window.innerHeight;
  canvas.width = view.width * devicePixelRatio; canvas.height = view.height * devicePixelRatio;
  canvas.style.width = view.width + "px"; canvas.style.height = view.height + "px";
  ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0);
  fitView();
  draw();
}
function toWorld(mx, my) {
  return { x: (mx - transform.x) / transform.scale, y: (my - transform.y) / transform.scale };
}
function visible(node) {
  return !hiddenLayers.has(node.layer) && !hiddenStatus.has(node.status);
}
function draw() {
  ctx.save();
  ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, view.width, view.height);
  ctx.translate(transform.x, transform.y); ctx.scale(transform.scale, transform.scale);
  for (const edge of DATA.edges) {
    const a = byId.get(edge.from), b = byId.get(edge.to);
    if (!a || !b || !visible(a) || !visible(b)) continue;
    const highlight = pinned && (edge.from === pinned || edge.to === pinned);
    ctx.strokeStyle = highlight ? "#1a4a7a" : (edge.status === "proposed" ? "rgba(180,195,210,.35)" : "rgba(150,166,182,.45)");
    ctx.lineWidth = (highlight ? 1.6 : 0.6) / transform.scale;
    ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
  }
  for (const node of DATA.nodes) {
    if (!visible(node)) continue;
    const r = 2.6 + Math.min(9, Math.sqrt(node.degree) * 0.9);
    const match = matches.has(node.id);
    ctx.beginPath(); ctx.arc(node.x, node.y, r + (match || node.id === pinned ? 3 : 0), 0, Math.PI * 2);
    if (node.status === "blocked") { ctx.fillStyle = "#fff"; ctx.fill(); ctx.strokeStyle = "#c00"; ctx.lineWidth = 1.5; ctx.stroke(); }
    else { ctx.fillStyle = node.color; ctx.globalAlpha = node.status === "proposed" ? 0.45 : 0.95; ctx.fill(); ctx.globalAlpha = 1; }
    if (match) { ctx.strokeStyle = "#111"; ctx.lineWidth = 1.2; ctx.stroke(); }
  }
  ctx.restore();
  requestAnimationFrame(draw);
}
function nearest(mx, my) {
  const p = toWorld(mx, my); let best = null, bestD = 12;
  for (const node of DATA.nodes) {
    if (!visible(node)) continue;
    const d = Math.hypot(node.x - p.x, node.y - p.y);
    if (d < bestD) { best = node; bestD = d; }
  }
  return best;
}
canvas.addEventListener("mousemove", event => {
  const node = nearest(event.clientX, event.clientY);
  hovered = node;
  if (node) {
    tooltip.style.display = "block";
    tooltip.style.left = Math.min(event.clientX + 14, view.width - 330) + "px";
    tooltip.style.top = Math.min(event.clientY + 14, view.height - 140) + "px";
    tooltip.innerHTML = "<strong>" + node.id + "</strong><br>" + node.layer + " / " + node.status +
      " / degree " + node.degree + "<br>" + (node.meaning || "") +
      (node.falsifier ? "<br><em>falsifier:</em> " + node.falsifier : "");
  } else { tooltip.style.display = "none"; }
});
canvas.addEventListener("mousedown", () => {
  pinned = hovered && hovered.id; canvas.classList.add("dragging");
});
window.addEventListener("mouseup", () => canvas.classList.remove("dragging"));
window.addEventListener("mousemove", event => {
  if (!canvas.classList.contains("dragging")) return;
  transform.x += event.movementX; transform.y += event.movementY;
});
canvas.addEventListener("wheel", event => {
  event.preventDefault();
  const factor = Math.exp(-event.deltaY * 0.0015);
  const p = toWorld(event.clientX, event.clientY);
  transform.scale = Math.min(12, Math.max(0.15, transform.scale * factor));
  transform.x = event.clientX - p.x * transform.scale;
  transform.y = event.clientY - p.y * transform.scale;
}, { passive: false });
document.getElementById("reset").addEventListener("click", () => {
  pinned = null; matches = new Set(); document.getElementById("search").value = "";
  fitView();
});
document.getElementById("search").addEventListener("input", event => {
  const query = event.target.value.trim().toLowerCase();
  matches = new Set(query ? DATA.nodes.filter(n => n.id.toLowerCase().includes(query)).map(n => n.id) : []);
});
for (const box of document.querySelectorAll("input[data-status]")) {
  box.addEventListener("change", () => {
    box.checked ? hiddenStatus.delete(box.dataset.status) : hiddenStatus.add(box.dataset.status);
  });
}
const legend = document.getElementById("legend");
for (const layer of [...new Set(DATA.nodes.map(n => n.layer))].sort()) {
  const label = document.createElement("label");
  const dot = document.createElement("span"); dot.className = "dot"; dot.style.background = DATA.nodes.find(n => n.layer === layer).color;
  const box = document.createElement("input"); box.type = "checkbox"; box.checked = true;
  box.addEventListener("change", () => { box.checked ? hiddenLayers.delete(layer) : hiddenLayers.add(layer); });
  label.append(box, dot, document.createTextNode(layer));
  legend.append(label);
}
document.getElementById("stats").textContent =
  DATA.nodes.length + " nodes, " + DATA.edges.length + " edges";
window.addEventListener("resize", fit);
fit();
</script>
</body>
</html>
"""


def main() -> int:
    nodes, edges = load()
    positions = layout(nodes, edges)
    degree = degree_of(edges)
    HTML.write_text(build_html(nodes, edges, positions, degree))
    SVG.write_text(build_svg(nodes, edges, positions, degree))
    print(f"wrote {HTML.relative_to(ROOT)} ({HTML.stat().st_size:,} bytes)")
    print(f"wrote {SVG.relative_to(ROOT)} ({SVG.stat().st_size:,} bytes)")
    print(f"nodes: {len(nodes)}   edges: {len(edges)}   layers: {len({n.get('layer') for n in nodes})}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
