#!/usr/bin/env python3
"""Generate the market map view from map.jsonl. Never edit the view by hand."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / "docs" / "market" / "map.jsonl"
OUT = ROOT / "docs" / "market" / "README.md"


def main() -> int:
    records = [json.loads(line) for line in MAP.read_text().splitlines() if line.strip()]
    participants = {r["id"]: r for r in records if r["type"] == "participant"}
    flows = {r["id"]: r for r in records if r["type"] == "flow"}
    instruments = {r["id"]: r for r in records if r["type"] == "instrument"}
    mappings = [r for r in records if r["type"] == "mapping"]

    lines = ["# The market map, generated", "",
             "Generated by `scripts/render_market_map.py` from `map.jsonl`. Do not edit by hand. "
             "Nothing here is a position.",
             "",
             f"**{len(participants)} participants, {len(flows)} flows, {len(instruments)} instruments, "
             f"{len(mappings)} mappings.**", ""]

    order = {"rule": 0, "mandate": 1, "contract": 2, "capital": 3, "procedure": 4, "attention": 5,
             "latency": 6, "none": 7}
    for participant in sorted(participants.values(), key=lambda r: (order[r["constraint"]], r["id"])):
        lines.append(f"## {participant['name']}")
        lines.append("")
        lines.append(f"- **constraint**: {participant['constraint']}")
        lines.append(f"- **why they cannot stop**: {participant['constraint_note']}")
        lines.append(f"- **evidence**: {participant['evidence']}")
        lines.append(f"- **falsifier**: {participant['falsifier']}")
        own = [f for f in flows.values() if f["participant"] == participant["id"]]
        if own:
            lines.append("- **flows**:")
            for flow in own:
                instrument = instruments[flow["instrument"]]
                lines.append(f"  - `{flow['id']}` on a {flow['calendar']} clock, into "
                             f"`{instrument['id']}` ({instrument['concentration']}), observed "
                             f"{flow['observable']}")
                lines.append(f"    - size: {flow['size_note']}")
                lines.append(f"    - data: {flow['data_note']}")
        linked = [m for m in mappings if m["flow"] in {f["id"] for f in own}]
        if linked:
            lines.append("- **measured nodes that connect**:")
            for mapping in linked:
                lines.append(f"  - `{mapping['node']}` {mapping['relation']} `{mapping['flow']}`")
        lines.append("")

    lines.append("## Instruments, and how much of the transfer each keeps")
    lines.append("")
    lines.append("| instrument | concentration | capacity | node |")
    lines.append("|---|---|---|---|")
    for instrument in sorted(instruments.values(), key=lambda r: (r["concentration"], r["id"])):
        node = instrument.get("node") or "none, with a reason"
        lines.append(f"| `{instrument['id']}` | {instrument['concentration']} | {instrument['capacity_note']} | "
                     f"`{node}` |")
    lines.append("")
    lines.append("## How to read this")
    lines.append("")
    lines.append("The order of the sections is the order of force: a rule closes a position whether the owner "
                 "likes it or not, a contract binds one party, capital limits what a dealer can warehouse, a "
                 "procedure queues people, attention costs money to spend, and latency decides who is present. "
                 "A participant whose constraint is `none` cannot be used.")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
