#!/usr/bin/env python3
"""Generate docs/CURRENT.md from the thesis ledger.

CURRENT.md is a view, never a source. That is the whole point: the summary cannot go stale
because nobody maintains it by hand, and the idea can move as often as it likes.

Run: make current   (after appending a line to docs/theses/index.jsonl)
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_theses import ROOT, load_index  # noqa: E402

OUT = ROOT / "docs" / "CURRENT.md"


def unowned_rows() -> list[str]:
    owners = ROOT / "OWNERS.md"
    if not owners.exists():
        return []
    out = []
    for line in owners.read_text().splitlines():
        if line.startswith("|") and "TBD" in line:
            cells = [c.strip() for c in line.strip("|").split("|")]
            if cells:
                out.append(cells[0])
    return out


def render(records: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    by_status: dict[str, list[dict]] = {}
    for rec in records:
        if isinstance(rec, dict) and rec.get("id"):
            by_status.setdefault(rec.get("status", "unknown"), []).append(rec)
    for bucket in by_status.values():
        bucket.sort(key=lambda r: str(r.get("date", "")), reverse=True)

    lines = [
        "# Current position",
        "",
        "<!-- generated by scripts/render_current.py from docs/theses/index.jsonl -->",
        f"<!-- {now} -->",
        "",
        "Read this first. It is a view of the ledger, not the truth itself: the record for each",
        "thesis is its own file, and the ledger is append-only. Nothing here is a bible, and",
        "nothing here needs to stay true for more than a day.",
        "",
    ]

    active = by_status.get("active", [])
    lines.append("## Active theses")
    lines.append("")
    if active:
        lines.append("| id | thesis | owner | since | falsifier | note |")
        lines.append("|---|---|---|---|---|---|")
        for rec in active:
            falsifiers = rec.get("falsifiers") or []
            first = (falsifiers[0] if falsifiers else "none declared")
            lines.append(f"| `{rec['id']}` | {rec.get('title', '')} | {rec.get('owner', '')} "
                         f"| {rec.get('date', '')} | {first[:60]} | `{rec.get('note', '')}` |")
    else:
        lines.append("None recorded. The team is between theses. That is allowed.")
    lines.append("")

    parked = by_status.get("parked", [])
    if parked:
        lines.append("## Parked")
        lines.append("")
        lines.append("Real work, not the current direction. Kept, not deleted.")
        lines.append("")
        for rec in parked:
            lines.append(f"- `{rec['id']}` {rec.get('title', '')} ({rec.get('owner', '')}, "
                         f"{rec.get('date', '')}) -> `{rec.get('note', '')}`")
        lines.append("")

    for status, heading in (("superseded", "Superseded"), ("retired", "Retired")):
        bucket = by_status.get(status, [])
        if not bucket:
            continue
        lines.append(f"## {heading}")
        lines.append("")
        for rec in bucket:
            parents = ", ".join(f"`{p}`" for p in (rec.get("supersedes") or [])) or "nothing"
            lines.append(f"- `{rec['id']}` {rec.get('title', '')} ({rec.get('date', '')}), "
                         f"supersedes {parents} -> `{rec.get('note', '')}`")
        lines.append("")

    unowned = unowned_rows()
    if unowned:
        lines.append("## Unowned workstreams")
        lines.append("")
        lines.append("Nobody owns these yet, so nobody should write to their paths:")
        lines.append("")
        for row in unowned:
            lines.append(f"- {row}")
        lines.append("")

    lines += [
        "## How to move the idea",
        "",
        "1. Write the change down in your own file: `docs/theses/<id>.md`.",
        "2. Append one line to `docs/theses/index.jsonl` with `id`, `title`, `status`, `owner`,",
        "   `date`, `note`, `falsifiers`, `evidence`, and `supersedes` if it replaces another thesis.",
        "3. `make current` regenerates this page. `make check` validates the ledger.",
        "",
        "Supersede, never overwrite. The old record is evidence of what the team rejected, which is",
        "worth points in the note.",
        "",
        "Anything you are not ready to make a thesis yet goes in `docs/inbox/`.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    records = load_index()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(records))
    active = len([r for r in records if isinstance(r, dict) and r.get("status") == "active"])
    print(f"wrote {OUT.relative_to(ROOT)} from {len(records)} record(s), {active} active")
    return 0


if __name__ == "__main__":
    sys.exit(main())
