(** Order book engine with incremental recomputation.

    Maintains a bid/ask order book with fully immutable state. Per-level order
    storage uses [Order_id.Map] for O(log n) operations. Snapshots and stats are
    derived via an incremental computation engine: when an event is applied,
    only changed outputs recompute. *)

type t
(** Opaque handle to an order book instance. *)

val create : unit -> t
(** [create ()] returns a new empty order book. *)

val apply :
  t ->
  Market_types.event ->
  (Market_types.book_snapshot * Market_types.fill list) Serror.t
(** [apply book event] processes one market event. Returns
    [Ok (snapshot, fills)] on success, or [Error msg] if the referenced order
    does not exist. Fills contains any trades generated by matching crossing
    orders. *)

val apply_replay :
  t ->
  Market_types.event ->
  (Market_types.book_snapshot * Market_types.fill list) Serror.t
(** [apply_replay book event] applies a venue event without creating new fills.
    It is for reconstructing a book from an exchange feed. *)

val apply_exn : t -> Market_types.event -> Market_types.book_snapshot
(** [apply_exn book event] is like [apply] but raises on missing orders. *)

val get_snapshot : t -> Market_types.book_snapshot
(** [get_snapshot book] returns the current book snapshot (top 10 bid/ask
    levels, spread, mid, micro price). *)

val get_stats : t -> Market_types.book_stats
(** [get_stats book] returns aggregate statistics for the current book state
    (total size per side, level counts, spread, mid). *)

val order_count : t -> int
(** [order_count book] returns the total number of active orders. *)

val reset : t -> unit
(** [reset book] clears all orders and returns to empty state. *)

val validate : t -> unit Serror.t
(** [validate book] checks order ownership, price-level totals, sides, and
    sizes. *)
